// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using UnityEngine;
using System.Collections.Generic;

[RequireComponent(typeof(CharacterController))]

public class OVROrbitCamera : OVRPlayerController
{
		// Use this for initialization
	//void Start () {
	//	initial_x = gameObject.transform.position.x;
	//	initial_y = gameObject.transform.position.y;
//		initial_z = gameObject.transform.position.z;
//	}
}